name: Seichi
version: '${version}'
main: com.github.ardririy.seichi.Seichi
authors: [ ardririy ]
commands:
  ranking:
    description: ランキングを表示します
  trash:
    description: ゴミ箱を表示します
  status:
    description: 総採掘量を表示します
  tool:
    description: ツールを取り出せます
